CREATE TABLE adult_numeric_test (
age BIGINT,
workclass TEXT ENCODING DICT(32),
fnlwgt BIGINT,
education TEXT ENCODING DICT(32),
education_num BIGINT,
marital_status TEXT ENCODING DICT(32),
occupation TEXT ENCODING DICT(32),
relationship TEXT ENCODING DICT(32),
race TEXT ENCODING DICT(32),
gender TEXT ENCODING DICT(32),
capital_gain BIGINT,
capital_loss BIGINT,
hours_per_week BIGINT,
native_country TEXT ENCODING DICT(32),
income_bracket TEXT ENCODING DICT(32),
rowNum BIGINT,
workclass_numeric BIGINT,
occupation_numeric BIGINT,
education_numeric BIGINT,
native_country_numeric BIGINT,
relationship_numeric BIGINT,
race_numeric BIGINT,
gender_numeric BIGINT,
income_bracket_numeric BIGINT,
marital_status_numeric BIGINT);

